import cStringIO
import re
import sys


class ControlFlowException(Exception):
  """Base class for exceptions related to control flow in generated code.

  Not strictly necessary, but useful for documentation purposes."""
  pass


class Continue(ControlFlowException):
  """Exception raised by the NEXT template directive."""
  pass


class Break(ControlFlowException):
  """Exception raised by the LAST template directive."""
  pass


class StringBuffer:
  """A wrapper around a StringIO object that stringifies all of its
  arguments before writing them.  Provides a handful of other useful
  methods as well.
  """

  def __init__(self, contents=None):
    """Initializes the object.  If the contents argument is not None, it
    is immediately passed to the write method.
    """
    self.__buffer = cStringIO.StringIO()
    if contents is not None:
      self.write(contents)

  def write(self, *args):
    """Stringifies each argument in turn and writes it to the internal
    buffer.
    """
    for arg in args:
      self.__buffer.write(str(arg))

  def clear(self):
    """Clears the contents of the internal buffer."""
    self.__buffer.seek(0)
    self.__buffer.truncate(0)

  def reset(self, *args):
    """Clears the internal buffer, then passes all of the arguments
    to the write method.
    """
    self.clear()
    self.write(*args)

  def get(self):
    """Returns the contents of the internal buffer."""
    return self.__buffer.getvalue()


class Error(Exception):
  """A trivial local exception class."""
  pass


class Literal:
  """A trivial wrapper for a template supplied as a string.

  This class is necessary so that the framework can distinguish a string
  meant to be a file or block name from a string meant to be the contents
  of a template.  The Perl version of the Toolkit requires one to pass in
  the latter type of string via a reference, but such semantics are
  unidiomatic and awkward in Python.

  A user shouldn't typically need to make explicit use of this class,
  but should just call Template.processString rather than Template.process.
  One may, however, pass a Literal to Template.process if one has a mind to.
  """

  # TODO: Re-engineer the way the PyTT passes document identifiers around
  # to make this class unnecessary.

  def __init__(self, text):
    self.__text = text

  def text(self):
    return self.__text


class PerlScalar:
  """An object wrapper that imposes certain aspects of Perl's scalar
  semantics on the wrapped object.

  First, the wrapped object is expressed as a string or number, as the
  situation warrants.  Strings are converted to numbers using Perl's
  rules: extra characters beyond the leading numeric portion are ignored,
  and a string that does not have a leading numeric portion is converted
  to zero.  If the wrapped object is a Python boolean, then True is
  stringified to "1", and False is stringified to "".  None is also
  stringified to "".  In a numeric context, True becomes 1, and False
  becomes 0.

  Second, all of the arithmetic and logical operations supported by the
  Template Toolkit's template language are supported between two
  PerlScalars, and result in another PerlScalar.  These operations
  include addition, subtraction, multiplication, division, division
  with truncation, and the Boolean operations and, or, and not.  The
  usual Boolean comparisons (==, !=, >, >=, <, and <=) are supported;
  the truth value is returned wrapped in another PerlScalar.  The cmp
  operator is also supported, the returned integer is wrapped in a
  PerlScalar.

  Third, the truth value of the wrapped value is evaluated according
  to Perl's rules: only the strings "" and "0" and the numeric value
  0 are considered false; everything else is true.  Python's False literal
  is also considered false.

  The wrapped value can be retrieved with the value() method.

  This class also has some additional semantics that enable its objects to
  be dropped in to expressions generated by the PyTT parser.

  The bitwise-and operator performs string concatenation.

  Iteration is dispatched to the wrapped object.

  PerlScalars may be placed on the right-hand side of the exponentiation
  operator.  The result of the expression is another PerlScalar object
  that wraps the same object, but which its truth value frozen to true.
  The left-hand side of the exponentiation is ignored.  This awkward
  construction is necessary to support the template language's ternary
  operator; "a ? b : c" in a template becomes "a and 1**b or c" in
  the generated code.  Furthermore, the frozen truth value is "sticky".
  In any arithmetic operating involving two PerlScalars, if the left-hand
  operand has a frozen truth value, the resulting PerlScalar has the
  same frozen truth value.  This is so that a template expression such as
  "a ? b + c : d + e" can be converted to a generated expression like
  "a and 1**b + c or d + e".

  Examples:

  PerlScalar(1) + PerlScalar(2) --> PerlScalar(3)

  PerlScalar('4 mississippi') / PerlScalar('  1.0e-2') --> PerlScalar(400.0)

  PerlScalar('text') + PerlScalar(3) --> PerlScalar(3)

  PerlScalar('1') and PerlScalar('0') --> PerlScalar(True)

  not PerlScalar('stuff') --> PerlScalar(False)

  PerlScalar('foo') & PerlScalar('bar') --> PerlScalar('foobar')

  PerlScalar(None) & PerlScalar(True) & PerlScalar(False) --> PerlScalar('1')

  PerlScalar(True) / PerlScalar(4) --> PerlScalar(0.25)

  list(PerlScalar([1, 2, 3])) --> [1, 2, 3]  # (A copy of the wrapped list)

  bool(PerlScalar([])) --> True

  bool(1**PerlScalar(False)) --> True

  (1**PerlScalar(False)).value() --> False
  """

  __False = (False, 0, "", "0")

  def __init__(self, value, truth=None):
    if isinstance(value, PerlScalar):
      # Sanity check: One PerlScalar should never need to wrap another.
      raise Error("Attempted to wrap a PerlScalar (%s) in another PerlScalar" %
                  value)
    self.__value = value
    self.__truth = truth

  def value(self):
    return self.__value

  def __add__(self, other):
    return PerlScalar(self.__numify() + other.__numify(), self.__truth)

  def __sub__(self, other):
    return PerlScalar(self.__numify() - other.__numify(), self.__truth)

  def __mul__(self, other):
    return PerlScalar(self.__numify() * other.__numify(), self.__truth)

  def __div__(self, other):
    return PerlScalar(self.__numify() / other.__numify(), self.__truth)

  def __mod__(self, other):
    return PerlScalar(self.__numify() % other.__numify(), self.__truth)

  def __floordiv__(self, other):
    return PerlScalar(self.__numify() // other.__numify(), self.__truth)

  # TODO: Figure out if any refinements are needed to the following
  # boolean comparisons.  For example, in Perl, "5foo" == 5, but
  # PerlScalar("5foo") != PerlScalar(5), because the wrapped Python
  # objects are being compared directly, and strings never equal integers.
  # All tests pass as-is, so I'm deferring investigation.  For complete
  # correctness, it may become necessary to store both the string and
  # numeric versions of the wrapped value, somewhat the way Perl scalar
  # are handled under the hood.

  def __eq__(self, other):
    return PerlScalar(self.__value == other.__value)

  def __ne__(self, other):
    return PerlScalar(self.__value != other.__value)

  def __gt__(self, other):
    return PerlScalar(self.__value > other.__value)

  def __ge__(self, other):
    return PerlScalar(self.__value >= other.__value)

  def __lt__(self, other):
    return PerlScalar(self.__value < other.__value)

  def __le__(self, other):
    return PerlScalar(self.__value <= other.__value)

  def __cmp__(self, other):
    return PerlScalar(cmp(self.__value, other.__value))

  def __and__(self, other):
    """String concatenation."""
    return PerlScalar("%s%s" % (self.__value, other.__value))

  def __rpow__(self, _):
    """Returns a new wrapper, with its truth value frozen to True, for the
    same object wrapped by this object.
    """
    return PerlScalar(self.__value, True)

  def __nonzero__(self):
    """Evaluates the truth of the wrapped object according to Perl's notion
    of truth.  If this object's truth value has been frozen, report that
    instead.
    """
    if self.__truth is not None:
      return self.__truth
    else:
      return self.__value not in self.__False

  def __invert__(self):
    return PerlScalar(not self)

  def __int__(self):
    return int(self.__numify())

  def __long__(self):
    return long(self.__numify())

  def __float__(self):
    return float(self.__numify())

  def __iter__(self):
    return iter(self.__value)

  def __str__(self):
    if self.__value is True:
      return "1"
    elif self.__value is False or self.__value is None:
      return ""
    else:
      return str(self.__value)

  def __numify(self):
    return numify(self.__value)


# A regular expression object that identifies an integer or floating-point
# number, the latter optionally in scientific notation.

NUMBER_RE = re.compile(r"\s*[-+]?(?:\d+(\.\d*)?|(\.\d+))([Ee][-+]?\d+)?")


def numify(value):
  """Converts any object to a number using Perl's rules."""
  if isinstance(value, (int, long, float)):
    return value
  elif value is True:
    return 1
  elif value is False:
    return 0
  match = NUMBER_RE.match(str(value))
  if not match:
    return 0
  elif match.group(1) or match.group(2) or match.group(3):
    return float(match.group(0))
  else:
    return long(match.group(0))


def unindent(code):
  """Unindents a multiline block of text.

  Removes a number of leading whitespace characters from each line
  equal to the smallest number of leading whitespace characters found
  on any line, excluding lines consisting solely of whitespace characters.
  """
  try:
    indent = min(len(match.group())
                 for match in re.finditer(r"(?m)^\s+(?=\S)", code))
  except ValueError:
    # No indentation found; min() complains of a zero-length sequence.
    pass
  else:
    code = re.sub(r"(?m)^.{%d}" % indent, "", code)
  return code


def EvaluateCode(code, context, stash):
  """Evaluates 
  """
  code = unindent(code)
  old_stdout = sys.stdout
  sys.stdout = tmpbuf = cStringIO.StringIO()
  try:
    exec code in {"context": context, "stash": stash}
  finally:
    sys.stdout = old_stdout
  return tmpbuf.getvalue()


def unscalar(arg):
  """Unwraps a PerlScalar object.

  If the sole argument is a PerlScalar, returns the value wrapped by
  that object; otherwise just returns the argument.
  """
  if isinstance(arg, PerlScalar):
    return arg.value()
  else:
    return arg


def unscalar_lex(arg):
  """Lexically unwraps a string containing a string or numeric constant,
  such as are created by the PyTT parser.

  If the argument (presumed to be a string) starts with the string "scalar("
  and ends with the string ")", evaluates and returns the portion of the
  argument between those strings; otherwise just returns the argument.
  """
  if arg.startswith("scalar(") and arg.endswith(")"):
    return eval(arg[7:-1])
  else:
    return arg


def unscalar_list(seq):
  """Creates and returns a list containing the results of applying the
  unscalar function to each element in seq, a sequence.

  If seq is not a sequence, returns an empty list.
  """
  try:
    return [unscalar(item) for item in seq]
  except TypeError:
    # seq is not a sequence.
    return []


def ScalarList(*args):
  """Returns a PerlScalar that wraps a list containing the result of
  applying the unscalar function to each argument of this function--
  except for xrange objects, which are flattened into the output list
  instead.
  """
  list = []
  for arg in args:
    if isinstance(arg, xrange):
      list.extend(arg)
    else:
      list.append(unscalar(arg))
  return PerlScalar(list)


def ScalarDictionary(*pairs):
  """Applies the unscalar function to each element of each two-element
  tuple in pairs, constructs a dictionary from the unscalared pairs,
  and returns the dictionary, wrapped in a PerlScalar.
  """
  return PerlScalar(dict((unscalar(key), unscalar(val)) for key, val in pairs))


def SwitchList(arg):
  """If arg (a PerlScalar) wraps a sequence type (other than a string),
  arg is returned; otherwise, a PerlScalar that wraps a single-element
  list containing the value wrapped by arg is returned.

  The function's name reflects its utility in executing the SWITCH
  template directive.
  """
  value = arg.value()
  if is_seq(value):
    return arg
  else:
    return ScalarList(value)


def Concatenate(*args):
  """Constructs the string resulting from concatenating the stringified
  arguments to this function, in order, then returns that string wrapped
  in a PerlScalar.
  """
  return PerlScalar("".join(str(x) for x in args))


def can(object, method):
  """Returns true iff object has a callable attribute with the given name."""
  return callable(getattr(object, method, None))


def chop(seq, count):
  """Returns an iterator that traverses the given sequence, returning tuples
  of count items at a time.  The final tuple is padded with Nones if there
  aren't enough items in the sequence.
  """
  buf = []
  for elt in seq:
    buf.append(elt)
    if len(buf) == count:
      yield tuple(buf)
      buf[:] = []
  if buf:
    yield tuple(buf) + (None,) * (count - len(buf))


def unpack(seq, n):
  """Returns the first tuple generated by chop(seq, n).

  This function provides semantics similar to Perl's

  ($a, $b, $c) = func();

  One may say:

  a, b, c = unpack(func(), 3)

  ...and not suffer an error if there are fewer than three elements
  in the tuple returned by func.
  """
  return chop(seq, n).next()


def listify(arg):
  """If arg is a list, returns arg; otherwise returns a single-element
  list containing arg.
  """
  if isinstance(arg, list):
    return arg
  else:
    return [arg]


def is_seq(obj):
  """Returns true iff obj is any object, other than a string, that
  supports iteration.
  """
  try:
    iter(obj)
  except TypeError:
    return False
  else:
    return not isinstance(obj, basestring)


def slice(seq, indices):
  """Performs a Perl-style slice, substituting None for out-of-range
  indices rather than raising an exception.
  """
  sliced = []
  for index in indices:
    try:
      sliced.append(seq[int(index)])
    except IndexError:
      sliced.append(None)
  return sliced
